### ISSUE TITLE
Options for bulk create/update/delete

### ISSUE THREAD

**Issue by sdmels** [reststate/reststate-mobx#128]
It would be very helpful if the library allows the creation of data on the server by passing an array of object and similarly perform a bulk delete option when passed an array of objects

**Comment by CodingItWrong** [comment]
This library follows the JSON:API spec, and I'm not aware of a way currently in JSON:API to do a bulk-create or bulk-delete. This is a known need that a lot of folks in the JSON:API community are asking for. The current state of the need is that there is an "Atomic Operations" extension to the spec that is being considered for JSON:API 1.1 but is not yet merged: https://github.com/json-api/json-api/pull/1437 - Because this isn't yet in the JSON:API spec, this client library can't support it either.

Apart from _spec_ support for bulk operations, there would also be the possibility of _client_ support for bulk operations, where you could pass a method multiple records to create/delete, and it would result in multiple calls to the server. This should be fairly easy for users of the library to implement with a loop, so I don't see a strong need to add it to the library itself. Adding it to the library raises additional questions about whether the requests should be sequential or parallelized, things that the client application is better suited to decide.

I'll close this issue for now, but feel free to reopen if I've misunderstood your request or you see something in the JSON:API spec that I missed.
