### ISSUE TITLE
observable on update

### ISSUE THREAD

**Issue by guillaumelebovic** [reststate/reststate-mobx#139]
Hello,
I'm a beginner so my apologize if the answer is obvious but it seems that when you update a single record like :

store.fooStore.byId({id: "1"}).update({attributes: {baz: ''bar"}})

=> this does not trigger the "observable" of the this ResourceStore.

the problem is that I would like a FlatList to refresh just after the update but it does not...
        <FlatList
          data={store.fooStore.records.slice()}
          keyExtractor={(item) => item.id}
          renderItem={
            ({item}) => <{......}>
          }
        />

Am I missing something?

Many thanks.

EDIT 1 : 
Just patched it like : 
    const storeRecord = records => newRecord => {
      const currentIndex = records.map((item) => item.id).indexOf(newRecord.id)
      const existingRecord = records.find(r => r.id === newRecord.id);
      if (currentIndex !== -1) {
          records[currentIndex] = newRecord;
      }
    };
    this.byId({ id: identifiant }).update({attributes: attributes}).then(response => {
      const record = new Resource({
        record: response.data,
        client: this.client,
        store: this,
      })
      runInAction(() => {
        storeRecord(this.records)(record);
      });
      return record;
    })

**Comment by CodingItWrong** [comment]
Using Mobx with React Native FlatLists is definitely tricky, due to the way they render. Here's a GitHub Issue that describes it:

https://github.com/mobxjs/mobx/issues/1142

I just tried to get this working by following these instructions, but I wasn't able to do so—I'm not sure why. Your best bet is probably to try to find updated information on using MobX with React Native FlatLists, or open a new issue that shows that you're following the instructions in <https://github.com/mobxjs/mobx/issues/1142> and it's still not working.

I wish I could provide more help; I'm just not quite sure what's going on inside MobX here =\
